import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const programs = [
  {
    name: "Forschungszulage",
    shortName: "FZulG",
    provider: "BAFA",
    description: "Steuerliche Förderung für Forschung und Entwicklung. Bis zu 25% der F&E-Personalkosten werden erstattet.",
    type: "TAX",
    maxAmount: 1000000,
    minAmount: 0,
    fundingRate: 25,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.forschungszulage.de",
    isActive: true,
  },
  {
    name: "Digital Jetzt",
    shortName: "Digital Jetzt",
    provider: "BMWK",
    description: "Zuschüsse für Investitionen in digitale Technologien und Qualifizierung der Mitarbeiter.",
    type: "GRANT",
    maxAmount: 50000,
    minAmount: 17000,
    fundingRate: 40,
    isRecurring: false,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.bmwk.de/digital-jetzt",
    isActive: true,
  },
  {
    name: "ERP-Digitalisierungskredit",
    shortName: "ERP-Digi",
    provider: "KfW",
    description: "Günstiger Kredit für Digitalisierungsvorhaben. Bis zu 25 Mio. Euro mit Zinsvorteil.",
    type: "LOAN",
    maxAmount: 25000000,
    minAmount: 25000,
    fundingRate: 0,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.kfw.de/digitalisierung",
    isActive: true,
  },
  {
    name: "Bundesförderung Energieeffizienz",
    shortName: "BEW",
    provider: "BAFA",
    description: "Förderung von Maßnahmen zur Steigerung der Energieeffizienz in Unternehmen.",
    type: "GRANT",
    maxAmount: 500000,
    minAmount: 0,
    fundingRate: 30,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: true,
    requiresExport: false,
    url: "https://www.bafa.de/bew",
    isActive: true,
  },
  {
    name: "ZIM - Zentrales Innovationsprogramm",
    shortName: "ZIM",
    provider: "BMWK",
    description: "Förderung von Forschungs- und Entwicklungsprojekten für innovative Produkte und Verfahren.",
    type: "GRANT",
    maxAmount: 380000,
    minAmount: 0,
    fundingRate: 35,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.zim.de",
    isActive: true,
  },
  {
    name: "go-digital",
    shortName: "go-digital",
    provider: "BMWK",
    description: "Beratungsförderung für kleine und mittlere Unternehmen in den Bereichen Digitalisierung.",
    type: "GRANT",
    maxAmount: 16500,
    minAmount: 0,
    fundingRate: 50,
    isRecurring: false,
    targetSizes: ["MICRO", "SMALL"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.bmwk.de/go-digital",
    isActive: true,
  },
  {
    name: "Innovationskredit Bayern",
    shortName: "IKB",
    provider: "LfA Bayern",
    description: "Günstiger Kredit für innovative Vorhaben in Bayern.",
    type: "LOAN",
    maxAmount: 5000000,
    minAmount: 25000,
    fundingRate: 0,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["BY"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.lfa.de",
    isActive: true,
  },
  {
    name: "Digitalbonus Bayern",
    shortName: "Digitalbonus",
    provider: "Bayern",
    description: "Zuschuss für Digitalisierungsprojekte in bayerischen Unternehmen.",
    type: "GRANT",
    maxAmount: 50000,
    minAmount: 0,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["BY"],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.digitalbonus.bayern",
    isActive: true,
  },
  {
    name: "Gründerland Bayern",
    shortName: "GLB",
    provider: "Bayern",
    description: "Unterstützung für Existenzgründer und junge Unternehmen in Bayern.",
    type: "GRANT",
    maxAmount: 36000,
    minAmount: 0,
    fundingRate: 40,
    isRecurring: false,
    targetSizes: ["MICRO", "SMALL"],
    targetIndustries: [],
    targetStates: ["BY"],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.gruenderland.bayern",
    isActive: true,
  },
  {
    name: "Klimaschutzoffensive",
    shortName: "KSO",
    provider: "KfW",
    description: "Förderkredit für Klimaschutzmaßnahmen in Unternehmen.",
    type: "LOAN",
    maxAmount: 25000000,
    minAmount: 0,
    fundingRate: 0,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: true,
    requiresExport: false,
    url: "https://www.kfw.de/klimaschutz",
    isActive: true,
  },
  {
    name: "NRW.BANK Innovationskredit",
    shortName: "NRW Inno",
    provider: "NRW.BANK",
    description: "Zinsgünstiger Kredit für innovative Unternehmen in Nordrhein-Westfalen.",
    type: "LOAN",
    maxAmount: 10000000,
    minAmount: 25000,
    fundingRate: 0,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["NW"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.nrwbank.de",
    isActive: true,
  },
  {
    name: "Mittelstand Innovativ & Digital",
    shortName: "MID",
    provider: "NRW",
    description: "Förderung von Digitalisierung und Innovation für den NRW-Mittelstand.",
    type: "GRANT",
    maxAmount: 15000,
    minAmount: 0,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["NW"],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.mittelstand-innovativ-digital.nrw",
    isActive: true,
  },
];

async function main() {
  console.log("Seeding programs...");

  for (const program of programs) {
    await db.program.upsert({
      where: { id: program.shortName },
      update: program,
      create: {
        id: program.shortName,
        ...program,
      },
    });
    console.log(`✓ ${program.name}`);
  }

  console.log("\nDone! Seeded", programs.length, "programs");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
