import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const programs = [
  // =====================
  // === EU-PROGRAMME ===
  // =====================
  {
    id: "horizon-eic-accelerator",
    name: "EIC Accelerator",
    shortName: "EIC",
    provider: "EU - European Innovation Council",
    description: "Flaggschiff-Programm für Startups und KMU mit Breakthrough Innovation. Kombination aus Zuschuss (bis 2,5 Mio. €) und Equity (bis 15 Mio. €). Für Deep Tech, Green Tech, Health Tech.",
    type: "GRANT",
    maxAmount: 2500000,
    fundingRate: 70,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://eic.ec.europa.eu/eic-funding-opportunities/eic-accelerator_en",
    isActive: true,
  },
  {
    id: "horizon-eic-pathfinder",
    name: "EIC Pathfinder",
    shortName: "Pathfinder",
    provider: "EU - European Innovation Council",
    description: "Förderung für visionäre Forschung zur Entwicklung bahnbrechender Technologien. Für frühe Forschungsphasen (TRL 1-4). Open und Challenge Tracks.",
    type: "GRANT",
    maxAmount: 4000000,
    fundingRate: 100,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://eic.ec.europa.eu/eic-funding-opportunities/eic-pathfinder_en",
    isActive: true,
  },
  {
    id: "horizon-eic-transition",
    name: "EIC Transition",
    shortName: "Transition",
    provider: "EU - European Innovation Council",
    description: "Brücke zwischen Forschung und Markt. Für Technologien aus Pathfinder oder ERC Projekten. Validierung und Business Development.",
    type: "GRANT",
    maxAmount: 2500000,
    fundingRate: 100,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://eic.ec.europa.eu/eic-funding-opportunities/eic-transition_en",
    isActive: true,
  },
  {
    id: "horizon-eurostars",
    name: "Eurostars",
    shortName: "Eurostars",
    provider: "EU - Eureka",
    description: "Förderung internationaler F&E-Kooperationen für KMU. Mind. 2 Partner aus verschiedenen Eurostars-Ländern. Marktnahe Innovation.",
    type: "GRANT",
    maxAmount: 500000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: true,
    url: "https://www.eurostars-eureka.eu",
    isActive: true,
  },
  {
    id: "horizon-erc-starting",
    name: "ERC Starting Grant",
    shortName: "ERC Starting",
    provider: "EU - European Research Council",
    description: "Förderung exzellenter Nachwuchsforscher (2-7 Jahre nach PhD). Frontier Research in allen Wissenschaftsbereichen.",
    type: "GRANT",
    maxAmount: 1500000,
    fundingRate: 100,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://erc.europa.eu/funding/starting-grants",
    isActive: true,
  },
  {
    id: "eu-life",
    name: "LIFE Programm",
    shortName: "LIFE",
    provider: "EU - Europäische Kommission",
    description: "EU-Förderprogramm für Umwelt- und Klimaschutzprojekte. Für Naturschutz, Kreislaufwirtschaft, Klimaschutz und Clean Energy Transition.",
    type: "GRANT",
    maxAmount: 10000000,
    fundingRate: 60,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: true,
    requiresExport: false,
    url: "https://cinea.ec.europa.eu/programmes/life_en",
    isActive: true,
  },
  {
    id: "eu-digital-europe",
    name: "Digital Europe Programme",
    shortName: "DEP",
    provider: "EU - Europäische Kommission",
    description: "Förderung der digitalen Transformation Europas. Schwerpunkte: KI, Cybersecurity, HPC, Digital Skills, Digitale Transformation.",
    type: "GRANT",
    maxAmount: 5000000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: ["it"],
    targetStates: [],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://digital-strategy.ec.europa.eu/en/activities/digital-programme",
    isActive: true,
  },
  {
    id: "eu-cef-digital",
    name: "CEF Digital",
    shortName: "CEF",
    provider: "EU - Europäische Kommission",
    description: "Connecting Europe Facility für digitale Infrastruktur. 5G-Korridore, Backbone-Netze, Blockchain, Cloud-Infrastruktur.",
    type: "GRANT",
    maxAmount: 30000000,
    fundingRate: 75,
    isRecurring: true,
    targetSizes: ["SMALL", "MEDIUM", "LARGE"],
    targetIndustries: ["it"],
    targetStates: [],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://cinea.ec.europa.eu/programmes/connecting-europe-facility_en",
    isActive: true,
  },
  {
    id: "eu-innovation-fund",
    name: "EU Innovation Fund",
    shortName: "Innovation Fund",
    provider: "EU - Europäische Kommission",
    description: "Einer der weltweit größten Fonds für klimafreundliche Technologien. Für innovative Low-Carbon Technologien, CCS, erneuerbare Energien.",
    type: "GRANT",
    maxAmount: 100000000,
    fundingRate: 60,
    isRecurring: true,
    targetSizes: ["SMALL", "MEDIUM", "LARGE"],
    targetIndustries: ["energy", "manufacturing"],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: true,
    requiresExport: false,
    url: "https://climate.ec.europa.eu/eu-action/funding-climate-action/innovation-fund_en",
    isActive: true,
  },
  {
    id: "eu-invest",
    name: "InvestEU",
    shortName: "InvestEU",
    provider: "EU - Europäische Investitionsbank",
    description: "EU-Garantieprogramm für Investitionen. Zugang zu Finanzierung über Finanzintermediäre. Für nachhaltige Infrastruktur, Innovation, KMU.",
    type: "GUARANTEE",
    maxAmount: 25000000,
    fundingRate: 0,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://investeu.europa.eu",
    isActive: true,
  },
  {
    id: "eu-cosme",
    name: "Single Market Programme (ex-COSME)",
    shortName: "SMP",
    provider: "EU - Europäische Kommission",
    description: "Förderung der Wettbewerbsfähigkeit von KMU. Marktzugang, Unternehmertum, günstige Rahmenbedingungen. Zugang zu Finanzmitteln.",
    type: "GRANT",
    maxAmount: 500000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: true,
    url: "https://single-market-economy.ec.europa.eu/sme-policy_en",
    isActive: true,
  },
  {
    id: "eu-ai-act-compliance",
    name: "EU AI Act Compliance Förderung",
    shortName: "AI Compliance",
    provider: "EU - Europäische Kommission",
    description: "NEU 2026: Förderung für KMU zur Umsetzung des EU AI Acts. Beratung, Zertifizierung, technische Anpassungen, Dokumentation.",
    type: "GRANT",
    maxAmount: 200000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: ["it"],
    targetStates: [],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai",
    isActive: true,
  },
  {
    id: "eu-dpp",
    name: "Digital Product Passport Förderung",
    shortName: "DPP",
    provider: "EU / BMWK",
    description: "NEU 2026: Förderung zur Einführung digitaler Produktpässe gem. EU-Verordnung. Für Textil, Elektronik, Batterien, Bauprodukte.",
    type: "GRANT",
    maxAmount: 150000,
    fundingRate: 40,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: ["manufacturing", "retail"],
    targetStates: [],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: true,
    requiresExport: false,
    url: "https://www.bmwk.de",
    isActive: true,
  },
  {
    id: "eu-chips-act",
    name: "EU Chips Act Förderung",
    shortName: "Chips Act",
    provider: "EU - Europäische Kommission",
    description: "Förderung der europäischen Halbleiterindustrie. Für Chip-Design, Fertigung, Packaging, Equipment, Materialien.",
    type: "GRANT",
    maxAmount: 50000000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["SMALL", "MEDIUM", "LARGE"],
    targetIndustries: ["manufacturing", "it"],
    targetStates: [],
    requiresRD: true,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://commission.europa.eu/strategy-and-policy/priorities-2019-2024/europe-fit-digital-age/european-chips-act_en",
    isActive: true,
  },

  // =====================
  // === BUNDESWEIT ===
  // =====================
  {
    id: "forschungszulage",
    name: "Forschungszulage",
    shortName: "FZulG",
    provider: "BAFA / Finanzamt",
    description: "Steuerliche Förderung für F&E. 25% der Personalkosten für Forschung werden erstattet. Rückwirkend beantragbar. Kombinierbar mit anderen Förderungen.",
    type: "TAX",
    maxAmount: 1000000,
    fundingRate: 25,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.forschungszulage.de",
    isActive: true,
  },
  {
    id: "zim",
    name: "ZIM - Zentrales Innovationsprogramm Mittelstand",
    shortName: "ZIM",
    provider: "BMWK",
    description: "Förderung von F&E-Projekten für innovative Produkte und Verfahren. Einzel- und Kooperationsprojekte. Marktnahe Forschung.",
    type: "GRANT",
    maxAmount: 380000,
    fundingRate: 35,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.zim.de",
    isActive: true,
  },
  {
    id: "exist-gruenderstipendium",
    name: "EXIST-Gründerstipendium",
    shortName: "EXIST",
    provider: "BMWK",
    description: "Stipendium für Gründer aus der Hochschule. Bis 3.000€/Monat für 1 Jahr + 30.000€ Sachkosten + 5.000€ Coaching.",
    type: "GRANT",
    maxAmount: 150000,
    fundingRate: 100,
    isRecurring: false,
    targetSizes: ["MICRO"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.exist.de",
    isActive: true,
  },
  {
    id: "exist-forschungstransfer",
    name: "EXIST-Forschungstransfer",
    shortName: "EXIST-FT",
    provider: "BMWK",
    description: "Für forschungsbasierte Gründungen mit aufwändiger Entwicklung. Phase 1: bis 250.000€, Phase 2: bis 180.000€.",
    type: "GRANT",
    maxAmount: 250000,
    fundingRate: 100,
    isRecurring: false,
    targetSizes: ["MICRO"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.exist.de",
    isActive: true,
  },
  {
    id: "go-digital",
    name: "go-digital",
    shortName: "go-digital",
    provider: "BMWK",
    description: "Beratungsförderung für KMU: Digitalisierte Geschäftsprozesse, Digitale Markterschließung, IT-Sicherheit. Über autorisierte Beratungsunternehmen.",
    type: "GRANT",
    maxAmount: 16500,
    fundingRate: 50,
    isRecurring: false,
    targetSizes: ["MICRO", "SMALL"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.bmwk.de/go-digital",
    isActive: true,
  },
  {
    id: "go-inno",
    name: "go-inno",
    shortName: "go-inno",
    provider: "BMWK",
    description: "Innovationsgutscheine für KMU. Beratung zu Produkt- und Verfahrensinnovationen. Innovationsmanagement.",
    type: "GRANT",
    maxAmount: 20000,
    fundingRate: 50,
    isRecurring: false,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.innovation-beratung-foerderung.de",
    isActive: true,
  },
  {
    id: "invest-bafa",
    name: "INVEST - Zuschuss für Wagniskapital",
    shortName: "INVEST",
    provider: "BAFA",
    description: "25% Zuschuss für Business Angels bei Investment in Startups. Macht dein Startup attraktiver für Investoren. Min. 25.000€ Investment.",
    type: "GRANT",
    maxAmount: 100000,
    fundingRate: 25,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.bafa.de/invest",
    isActive: true,
  },
  {
    id: "erp-digitalisierung",
    name: "ERP-Digitalisierungskredit",
    shortName: "ERP-Digi",
    provider: "KfW",
    description: "Günstiger Kredit für Digitalisierung und Innovation. Für Investitionen in digitale Produkte, Prozesse und Strategien.",
    type: "LOAN",
    maxAmount: 25000000,
    fundingRate: 0,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.kfw.de/inlandsfoerderung/Unternehmen/Digitalisierung/",
    isActive: true,
  },
  {
    id: "erp-gruenderkredit",
    name: "ERP-Gründerkredit StartGeld",
    shortName: "StartGeld",
    provider: "KfW",
    description: "Kredit für Gründer und junge Unternehmen bis 5 Jahre. Max. 125.000€, 80% Haftungsfreistellung durch KfW.",
    type: "LOAN",
    maxAmount: 125000,
    fundingRate: 0,
    isRecurring: false,
    targetSizes: ["MICRO", "SMALL"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.kfw.de/inlandsfoerderung/Unternehmen/Gr%C3%BCnden/",
    isActive: true,
  },
  {
    id: "kfw-klimaschutz",
    name: "Klimaschutzoffensive für Unternehmen",
    shortName: "KSO",
    provider: "KfW",
    description: "Förderkredit für Klimaschutzmaßnahmen. Günstige Konditionen für grüne Investitionen in 14 Kategorien.",
    type: "LOAN",
    maxAmount: 25000000,
    fundingRate: 0,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: true,
    requiresExport: false,
    url: "https://www.kfw.de/inlandsfoerderung/Unternehmen/Umwelt/",
    isActive: true,
  },
  {
    id: "bafa-energieeffizienz",
    name: "Bundesförderung für Energie- und Ressourceneffizienz",
    shortName: "EEW",
    provider: "BAFA",
    description: "Zuschuss für Energieeffizienzmaßnahmen. Module für Querschnittstechnologien, Prozesswärme, MSR, Abwärme, Ressourceneffizienz.",
    type: "GRANT",
    maxAmount: 15000000,
    fundingRate: 40,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: true,
    requiresExport: false,
    url: "https://www.bafa.de/DE/Energie/Energieeffizienz/energieeffizienz_node.html",
    isActive: true,
  },
  {
    id: "bafa-beratung",
    name: "Förderung unternehmerischen Know-hows",
    shortName: "BAFA Beratung",
    provider: "BAFA",
    description: "Zuschuss für Unternehmensberatung. Bis 80% für Jungunternehmen (< 2 Jahre), 50% für Bestandsunternehmen.",
    type: "GRANT",
    maxAmount: 4000,
    fundingRate: 80,
    isRecurring: false,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.bafa.de/DE/Wirtschaft/Beratung_Finanzierung/unternehmensberatung_node.html",
    isActive: true,
  },
  {
    id: "kmu-innovativ",
    name: "KMU-innovativ",
    shortName: "KMU-innovativ",
    provider: "BMBF",
    description: "Spitzenforschung für KMU in verschiedenen Technologiefeldern: IKT, Biotechnologie, Medizintechnik, Photonik, Produktionstechnologie.",
    type: "GRANT",
    maxAmount: 500000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.bmbf.de/bmbf/de/forschung/innovativer-mittelstand/kmu-innovativ/kmu-innovativ_node.html",
    isActive: true,
  },

  // =====================
  // === BAYERN ===
  // =====================
  {
    id: "digitalbonus-bayern",
    name: "Digitalbonus Bayern",
    shortName: "Digitalbonus BY",
    provider: "Freistaat Bayern",
    description: "Zuschuss für Digitalisierung: Hardware, Software, IT-Sicherheit, externe Dienstleistungen. Standard (10k) oder Plus (50k).",
    type: "GRANT",
    maxAmount: 50000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["BY"],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.digitalbonus.bayern",
    isActive: true,
  },
  {
    id: "innovationskredit-bayern",
    name: "Innovationskredit Bayern",
    shortName: "IKB",
    provider: "LfA Förderbank Bayern",
    description: "Zinsgünstiger Kredit für innovative Vorhaben. F&E und Markteinführung innovativer Produkte.",
    type: "LOAN",
    maxAmount: 5000000,
    fundingRate: 0,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["BY"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.lfa.de",
    isActive: true,
  },
  {
    id: "baytp",
    name: "BayTP - Bayerisches Technologieförderungsprogramm",
    shortName: "BayTP",
    provider: "Freistaat Bayern",
    description: "Förderung technologischer F&E-Projekte. Für KMU mit Sitz/Betriebsstätte in Bayern. Bis 50% der zuwendungsfähigen Kosten.",
    type: "GRANT",
    maxAmount: 250000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["BY"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.stmwi.bayern.de/foerderungen/baytp/",
    isActive: true,
  },

  // =====================
  // === BERLIN ===
  // =====================
  {
    id: "berlin-startup-stipendium",
    name: "Berlin Startup Stipendium",
    shortName: "BSS",
    provider: "Land Berlin / IBB",
    description: "2.000€/Monat für 12 Monate für Gründer in Berlin. Für innovative, technologieorientierte Geschäftsideen.",
    type: "GRANT",
    maxAmount: 24000,
    fundingRate: 100,
    isRecurring: false,
    targetSizes: ["MICRO"],
    targetIndustries: [],
    targetStates: ["BE"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.ibb.de/de/foerderprogramme/berlin-startup-stipendium.html",
    isActive: true,
  },
  {
    id: "berlin-gruendungsbonus",
    name: "GründungsBONUS Berlin",
    shortName: "GründungsBONUS",
    provider: "IBB Berlin",
    description: "Zuschuss für innovative Gründungen in Berlin. Für Personal, Sachausgaben, Investitionen. Bis 50.000€.",
    type: "GRANT",
    maxAmount: 50000,
    fundingRate: 50,
    isRecurring: false,
    targetSizes: ["MICRO", "SMALL"],
    targetIndustries: [],
    targetStates: ["BE"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.ibb.de",
    isActive: true,
  },
  {
    id: "berlin-proinno",
    name: "Pro FIT - Projektförderung",
    shortName: "Pro FIT",
    provider: "IBB Berlin",
    description: "Förderung von F&E-Projekten in Berlin. Experimentelle Entwicklung und Durchführbarkeitsstudien.",
    type: "GRANT",
    maxAmount: 400000,
    fundingRate: 45,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["BE"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.ibb.de/de/foerderprogramme/pro-fit.html",
    isActive: true,
  },

  // =====================
  // === NRW ===
  // =====================
  {
    id: "mid-nrw",
    name: "Mittelstand Innovativ & Digital",
    shortName: "MID",
    provider: "MWIKE NRW",
    description: "Innovationsassistent, Digitalisierungsprojekte, Potenzialberatungen für KMU in NRW.",
    type: "GRANT",
    maxAmount: 15000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["NW"],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.mittelstand-innovativ-digital.nrw",
    isActive: true,
  },
  {
    id: "progres-nrw",
    name: "progres.nrw - Klimaschutztechnik",
    shortName: "progres.nrw",
    provider: "Land NRW",
    description: "Förderung für Klimaschutz und Energieeffizienz in NRW. Verschiedene Module für unterschiedliche Maßnahmen.",
    type: "GRANT",
    maxAmount: 150000,
    fundingRate: 30,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: ["NW"],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: true,
    requiresExport: false,
    url: "https://www.progres.nrw",
    isActive: true,
  },

  // =====================
  // === BADEN-WÜRTTEMBERG ===
  // =====================
  {
    id: "innovationsgutschein-bw",
    name: "Innovationsgutschein BW",
    shortName: "Inno-Gutschein BW",
    provider: "Land Baden-Württemberg",
    description: "Gutschein für F&E-Dienstleistungen. Hightech (20.000€) und Standard (7.500€). Für externe Forschungsleistungen.",
    type: "GRANT",
    maxAmount: 20000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["BW"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.innovationsgutscheine.de",
    isActive: true,
  },
  {
    id: "startup-bw-preseed",
    name: "Start-up BW Pre-Seed",
    shortName: "Pre-Seed BW",
    provider: "Land Baden-Württemberg",
    description: "Frühphasenfinanzierung für innovative Startups in BW. Bis 200.000€ für technologieorientierte Gründungen.",
    type: "GRANT",
    maxAmount: 200000,
    fundingRate: 100,
    isRecurring: false,
    targetSizes: ["MICRO"],
    targetIndustries: [],
    targetStates: ["BW"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.startupbw.de",
    isActive: true,
  },

  // =====================
  // === SACHSEN ===
  // =====================
  {
    id: "technologiefoerderung-sachsen",
    name: "Technologieförderung Sachsen",
    shortName: "TechFörd SN",
    provider: "SAB Sachsen",
    description: "Förderung von F&E-Projekten in sächsischen Unternehmen. Einzelbetriebliche F&E, Verbundprojekte, Prozessinnovation.",
    type: "GRANT",
    maxAmount: 400000,
    fundingRate: 45,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["SN"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.sab.sachsen.de",
    isActive: true,
  },

  // =====================
  // === HAMBURG ===
  // =====================
  {
    id: "innorampup-hamburg",
    name: "InnoRampUp Hamburg",
    shortName: "InnoRampUp",
    provider: "IFB Hamburg",
    description: "Zuschuss für innovative Startups in Hamburg. Für Personal, Sachmittel, Investitionen. Bis 150.000€.",
    type: "GRANT",
    maxAmount: 150000,
    fundingRate: 100,
    isRecurring: false,
    targetSizes: ["MICRO", "SMALL"],
    targetIndustries: [],
    targetStates: ["HH"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.ifbhh.de/foerderprogramm/innorampup",
    isActive: true,
  },

  // =====================
  // === HESSEN ===
  // =====================
  {
    id: "digi-zuschuss-hessen",
    name: "DIGI-Zuschuss Hessen",
    shortName: "DIGI-Zuschuss",
    provider: "WIBank Hessen",
    description: "Zuschuss für Digitalisierung in hessischen KMU. Für IT-Hardware, Software, IT-Sicherheit, Prozessdigitalisierung.",
    type: "GRANT",
    maxAmount: 10000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["HE"],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.wibank.de",
    isActive: true,
  },

  // =====================
  // === NIEDERSACHSEN ===
  // =====================
  {
    id: "digitalbonus-niedersachsen",
    name: "Digitalbonus Niedersachsen",
    shortName: "Digitalbonus NDS",
    provider: "NBank",
    description: "Zuschuss für Digitalisierung in niedersächsischen KMU. Digitalbonus.Beratung und Digitalbonus.Invest.",
    type: "GRANT",
    maxAmount: 10000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL"],
    targetIndustries: [],
    targetStates: ["NI"],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.nbank.de",
    isActive: true,
  },

  // =====================
  // === THÜRINGEN ===
  // =====================
  {
    id: "gruenderpraemie-thueringen",
    name: "Thüringer Gründerprämie",
    shortName: "Gründerprämie TH",
    provider: "TAB Thüringen",
    description: "Zuschuss für technologieorientierte Gründungen in Thüringen. Für Personal, Investitionen, Beratung.",
    type: "GRANT",
    maxAmount: 100000,
    fundingRate: 65,
    isRecurring: false,
    targetSizes: ["MICRO", "SMALL"],
    targetIndustries: [],
    targetStates: ["TH"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.aufbaubank.de",
    isActive: true,
  },

  // =====================
  // === SCHLESWIG-HOLSTEIN ===
  // =====================
  {
    id: "startup-sh",
    name: "Seed- und StartUp-Förderung SH",
    shortName: "StartUp SH",
    provider: "WTSH / IB.SH",
    description: "Zuschuss für innovative Startups in Schleswig-Holstein. Bis 100.000€ für technologieorientierte Gründungen.",
    type: "GRANT",
    maxAmount: 100000,
    fundingRate: 70,
    isRecurring: false,
    targetSizes: ["MICRO", "SMALL"],
    targetIndustries: [],
    targetStates: ["SH"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.ib-sh.de",
    isActive: true,
  },

  // =====================
  // === BRANDENBURG ===
  // =====================
  {
    id: "brandenburgkredit-innovation",
    name: "BrandenburgKredit Innovativ",
    shortName: "BK Innovativ",
    provider: "ILB Brandenburg",
    description: "Zinsgünstiger Kredit für innovative Unternehmen in Brandenburg. Für F&E und Markteinführung.",
    type: "LOAN",
    maxAmount: 3000000,
    fundingRate: 0,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["BB"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.ilb.de",
    isActive: true,
  },

  // =====================
  // === MECKLENBURG-VORPOMMERN ===
  // =====================
  {
    id: "innovationsfoerderung-mv",
    name: "Technologie- und Innovationsförderung MV",
    shortName: "Inno MV",
    provider: "LFI MV",
    description: "Förderung von F&E-Projekten in Mecklenburg-Vorpommern. Einzelbetriebliche Projekte und Verbundprojekte.",
    type: "GRANT",
    maxAmount: 200000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["MV"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.lfi-mv.de",
    isActive: true,
  },

  // =====================
  // === SACHSEN-ANHALT ===
  // =====================
  {
    id: "ego-start-sachsenanhalt",
    name: "ego.-START Sachsen-Anhalt",
    shortName: "ego.-START",
    provider: "IB Sachsen-Anhalt",
    description: "Zuschuss für technologie- und wissensbasierte Gründungen in Sachsen-Anhalt.",
    type: "GRANT",
    maxAmount: 80000,
    fundingRate: 75,
    isRecurring: false,
    targetSizes: ["MICRO"],
    targetIndustries: [],
    targetStates: ["ST"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.ib-sachsen-anhalt.de",
    isActive: true,
  },

  // =====================
  // === BREMEN ===
  // =====================
  {
    id: "luft-bremen",
    name: "LUFT-Förderung Bremen",
    shortName: "LUFT",
    provider: "BAB Bremen",
    description: "Lohnkosten-Unterstützung für F&E in Bremen. Zuschuss zu Personalkosten für Forschungsprojekte.",
    type: "GRANT",
    maxAmount: 100000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["HB"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.bab-bremen.de",
    isActive: true,
  },

  // =====================
  // === RHEINLAND-PFALZ ===
  // =====================
  {
    id: "innovationsfoerderung-rlp",
    name: "Innovationsförderung Rheinland-Pfalz",
    shortName: "Inno RLP",
    provider: "ISB Rheinland-Pfalz",
    description: "Förderung für innovative Projekte in RLP. F&E-Projekte, Innovationsassistenten, Innovationsberatung.",
    type: "GRANT",
    maxAmount: 200000,
    fundingRate: 45,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["RP"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.isb.rlp.de",
    isActive: true,
  },

  // =====================
  // === SAARLAND ===
  // =====================
  {
    id: "meistergruendungspraemie-saar",
    name: "Meistergründungsprämie Saarland",
    shortName: "MGP Saar",
    provider: "SIKB Saarland",
    description: "Zuschuss für Handwerksgründungen und Unternehmensübernahmen im Saarland. Bis 10.000€.",
    type: "GRANT",
    maxAmount: 10000,
    fundingRate: 0,
    isRecurring: false,
    targetSizes: ["MICRO", "SMALL"],
    targetIndustries: ["construction"],
    targetStates: ["SL"],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.sikb.de",
    isActive: true,
  },
];

async function main() {
  console.log("🌱 Seeding programs...\n");

  let count = 0;
  for (const program of programs) {
    await db.program.upsert({
      where: { id: program.id },
      update: program,
      create: program,
    });
    console.log(`✓ ${program.shortName || program.name}`);
    count++;
  }

  console.log(`\n✅ Fertig! ${count} Programme in der Datenbank.`);
  
  // Stats
  const euPrograms = programs.filter(p => p.provider.includes("EU"));
  const bundesPrograms = programs.filter(p => !p.provider.includes("EU") && p.targetStates.length === 0);
  const regionalPrograms = programs.filter(p => p.targetStates.length > 0);
  
  console.log(`\n📊 Statistik:`);
  console.log(`   EU-Programme: ${euPrograms.length}`);
  console.log(`   Bundesweit: ${bundesPrograms.length}`);
  console.log(`   Regional: ${regionalPrograms.length}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
