import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const programs = [
  {
    id: "forschungszulage",
    name: "Forschungszulage",
    shortName: "FZulG",
    provider: "BAFA",
    description: "Steuerliche Förderung für Forschung und Entwicklung. Bis zu 25% der F&E-Personalkosten werden erstattet. Gilt für alle Branchen und Unternehmensgrößen.",
    type: "TAX",
    maxAmount: 1000000,
    fundingRate: 25,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.forschungszulage.de",
    isActive: true,
  },
  {
    id: "zim",
    name: "ZIM - Zentrales Innovationsprogramm",
    shortName: "ZIM",
    provider: "BMWK",
    description: "Förderung von Forschungs- und Entwicklungsprojekten für innovative Produkte, Verfahren und Dienstleistungen. Einzelprojekte und Kooperationen möglich.",
    type: "GRANT",
    maxAmount: 380000,
    fundingRate: 35,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.zim.de",
    isActive: true,
  },
  {
    id: "digital-jetzt",
    name: "Digital Jetzt",
    shortName: "Digital Jetzt",
    provider: "BMWK",
    description: "Zuschüsse für Investitionen in digitale Technologien und Qualifizierung der Mitarbeiter im Bereich Digitalisierung.",
    type: "GRANT",
    maxAmount: 50000,
    fundingRate: 40,
    isRecurring: false,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.bmwk.de/digital-jetzt",
    isActive: true,
  },
  {
    id: "go-digital",
    name: "go-digital",
    shortName: "go-digital",
    provider: "BMWK",
    description: "Beratungsförderung für KMU in den Bereichen IT-Sicherheit, digitale Markterschließung und digitalisierte Geschäftsprozesse.",
    type: "GRANT",
    maxAmount: 16500,
    fundingRate: 50,
    isRecurring: false,
    targetSizes: ["MICRO", "SMALL"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.bmwk.de/go-digital",
    isActive: true,
  },
  {
    id: "erp-digi",
    name: "ERP-Digitalisierungskredit",
    shortName: "ERP-Digi",
    provider: "KfW",
    description: "Günstiger Kredit für Digitalisierungsvorhaben. Finanzierung von Investitionen und Betriebsmitteln für die digitale Transformation.",
    type: "LOAN",
    maxAmount: 25000000,
    fundingRate: 0,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.kfw.de",
    isActive: true,
  },
  {
    id: "bew",
    name: "Bundesförderung Energieeffizienz",
    shortName: "BEW",
    provider: "BAFA",
    description: "Förderung von Maßnahmen zur Steigerung der Energieeffizienz und Nutzung erneuerbarer Energien in Unternehmen.",
    type: "GRANT",
    maxAmount: 500000,
    fundingRate: 30,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: true,
    requiresExport: false,
    url: "https://www.bafa.de",
    isActive: true,
  },
  {
    id: "kfw-klima",
    name: "Klimaschutzoffensive",
    shortName: "KSO",
    provider: "KfW",
    description: "Förderkredit für Klimaschutzmaßnahmen. Finanzierung von klimafreundlichen Investitionen zu günstigen Konditionen.",
    type: "LOAN",
    maxAmount: 25000000,
    fundingRate: 0,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: true,
    requiresExport: false,
    url: "https://www.kfw.de",
    isActive: true,
  },
  {
    id: "exist",
    name: "EXIST-Gründerstipendium",
    shortName: "EXIST",
    provider: "BMWK",
    description: "Stipendium für Studierende, Absolventen und Wissenschaftler zur Gründungsvorbereitung. Bis zu 3.000€/Monat plus Sachkosten.",
    type: "GRANT",
    maxAmount: 150000,
    fundingRate: 100,
    isRecurring: false,
    targetSizes: ["MICRO"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.exist.de",
    isActive: true,
  },
  {
    id: "digitalbonus-by",
    name: "Digitalbonus Bayern",
    shortName: "Digitalbonus",
    provider: "Bayern",
    description: "Zuschuss für Digitalisierungsprojekte in bayerischen Unternehmen. Hardware, Software und IT-Sicherheit.",
    type: "GRANT",
    maxAmount: 50000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["BY"],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.digitalbonus.bayern",
    isActive: true,
  },
  {
    id: "innovationskredit-by",
    name: "Innovationskredit Bayern",
    shortName: "IKB",
    provider: "LfA Bayern",
    description: "Zinsgünstiger Kredit für innovative Vorhaben in Bayern. F&E-Projekte und Markteinführung neuer Produkte.",
    type: "LOAN",
    maxAmount: 5000000,
    fundingRate: 0,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["BY"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.lfa.de",
    isActive: true,
  },
  {
    id: "mid-nrw",
    name: "Mittelstand Innovativ & Digital",
    shortName: "MID",
    provider: "NRW",
    description: "Förderung von Digitalisierung und Innovation für den NRW-Mittelstand. Beratung und Umsetzung.",
    type: "GRANT",
    maxAmount: 15000,
    fundingRate: 50,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["NW"],
    requiresRD: false,
    requiresDigital: true,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.mittelstand-innovativ-digital.nrw",
    isActive: true,
  },
  {
    id: "innovationskredit-nrw",
    name: "NRW.BANK Innovationskredit",
    shortName: "NRW Inno",
    provider: "NRW.BANK",
    description: "Zinsgünstiger Kredit für innovative Unternehmen in Nordrhein-Westfalen.",
    type: "LOAN",
    maxAmount: 10000000,
    fundingRate: 0,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM"],
    targetIndustries: [],
    targetStates: ["NW"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.nrwbank.de",
    isActive: true,
  },
  {
    id: "berlin-startup",
    name: "Berlin Startup Stipendium",
    shortName: "BSS",
    provider: "Berlin",
    description: "Stipendium für Gründer in Berlin. 2.000€/Monat für 12 Monate zur Entwicklung innovativer Geschäftsideen.",
    type: "GRANT",
    maxAmount: 24000,
    fundingRate: 100,
    isRecurring: false,
    targetSizes: ["MICRO"],
    targetIndustries: [],
    targetStates: ["BE"],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.berlin.de/sen/wirtschaft",
    isActive: true,
  },
  {
    id: "progres-nrw",
    name: "progres.nrw Klimaschutztechnik",
    shortName: "progres.nrw",
    provider: "NRW",
    description: "Förderung für Klimaschutz und Energieeffizienz in NRW. Breites Spektrum an förderfähigen Maßnahmen.",
    type: "GRANT",
    maxAmount: 150000,
    fundingRate: 30,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL", "MEDIUM", "LARGE"],
    targetIndustries: [],
    targetStates: ["NW"],
    requiresRD: false,
    requiresDigital: false,
    requiresGreen: true,
    requiresExport: false,
    url: "https://www.progres.nrw",
    isActive: true,
  },
  {
    id: "invest-bafa",
    name: "INVEST - Zuschuss für Wagniskapital",
    shortName: "INVEST",
    provider: "BAFA",
    description: "25% Zuschuss für Business Angels die in Startups investieren. Macht dein Startup attraktiver für Investoren.",
    type: "GRANT",
    maxAmount: 100000,
    fundingRate: 25,
    isRecurring: true,
    targetSizes: ["MICRO", "SMALL"],
    targetIndustries: [],
    targetStates: [],
    requiresRD: true,
    requiresDigital: false,
    requiresGreen: false,
    requiresExport: false,
    url: "https://www.bafa.de/invest",
    isActive: true,
  },
];

async function main() {
  console.log("🌱 Seeding programs...\n");

  for (const program of programs) {
    await db.program.upsert({
      where: { id: program.id },
      update: program,
      create: program,
    });
    console.log(`✓ ${program.name}`);
  }

  console.log(`\n✅ Done! Seeded ${programs.length} programs`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
